---
editor_options: 
  chunk_output_type: console
output: html_document
---

## Организация рабочего процесса: проекты

### Что является вашим достоянием

1. Это конечно среда, где хранятся данные --- список Envirinment

1. Но в первую очередь это конечно скрипты.

В принципе, то что я фиксирую свои ответы в книге --- это уже хорошо.
Есть конечно большая задача по тому, чтобы изучить как работает букдаун, чтобы понять как это дело работает.
Однако, меня это уже мало по-малу приучает к тому, чтобы работать скриптами.

### Где находится ваш анализ

В каталогах. Чтобы проверить можно воспользоваться командой `getwd()`

### Пути и каталоги

* Необходимо помнить что разделителем В Windows --- является обратная косая черта ('\'). А в Mac прямая --- ('/'). НАм рекомендуют использовать стиль Mac.

### Проекты RStudio

Начиная работу с этой книгой, я заглянул вперёд и предусмотрительно создал проект.
А если сохранять графики и данные консольным способом, то при поиске в системе помимо найденного объекта, будет находится ещё и скрипт, который сохранил его. Это поистине чудо!!!

```{r}
library("tidyverse")

ggplot(diamonds, aes(carat, price)) +
  geom_hex()
ggsave("diamonds.pdf")

write_csv(diamonds, "diamonds.csv")
```

### Резюме

Ниже приведен краткий перечень тех возможностей работы с R-кодом, который предлагает RStudio:

* Создавать проект RStudio для каждого проекта анализа

* Хранить в проекте файлы данных.

* Хранить в проекте скрипты, редактировать их и выполнять по частям или целиком

* Сохранять в проекте свои выходные результаты (графики и очищенные данные)

* использовать только относительные пути, а не абсолютные

Всё необходимое будет собрано в одном месте и отделено от других проектов с которымт я буду работать.

Говоря словами Эрика Картмана --- ЩЩЩЩикарна!


