---
editor_options: 
  chunk_output_type: console
output: html_document
---

## Организация рабочего процесса: скрипты

Здесь советуют юзать шорт-каты и окно скриптов.
Это забавно, потому что я с момента открытия книги использую R.markdown файлы, для ведения документа обучения.

```{r}
library("tidyverse")
library("viridis")
library("forcats")
library("nycflights13")
library("Lahman")
```

### Выполнение кода
Здесь снова советуют юзать шорт-каты. Спасибо, на самом деле очень своевременно. Без иронии.

А так же автор книги приучает к правилам хорошего тона - не вставлять в скрипты исполняющие на чужом компьютере строки кода типа скачивания пакетов `install.packeges()` или установки рабочей директории`setwd()`.

### Диагностические средства RStudio

Ошибки и предупреждения видны в окне исполнения скриптов.

#### Упражнение 6.3.1
<div class="question">
Go to the RStudio Tips twitter account, [https://twitter.com/rstudiotips](https://twitter.com/rstudiotips) and find one tip that looks interesting. Practice using it!
</div>

На самом деле, много интересных трюков - использование окна скрипта как в Vim для быстрого редактирования столбиком

Например, есть такое окно

```{}
А
А
А
А
```

нужно зажать "Option" на Маке, и "Alt" на Винде, курсор станет крестиком, необходимо выделить нужный столбец и можно редактировать сразу на всю строку. Это очень удобно.

```{}
"А", %>%
"А", %>%
"А", %>%
"А", %>%
```

А чтобы всё выстроить в линию, достачно сделать удаление после курсора - на маке комбинация клавиш `fn`+`delete`, на винде просто `bacspace`.

```{}
"А", %>% "А", %>% "А", %>% "А", %>%
```

Огонь просто.

#### Упражнение 6.3.2
<div class="question">
What other common mistakes will RStudio diagnostics report? Read [Code diagnostics](https://support.rstudio.com/hc/en-us/articles/205753617-Code-Diagnostics) to find out.
</div>

1. Проверка отсутствия, несогласованности, частично согласованности и большого количества аргументов для функций

1. Предупреждение, если переменная не определена

1. Предупреждение, если переменная определена, но не используется

1. [Hadley Wickham’s style guide](http://adv-r.had.co.nz/Style.html)

1. [Format R code automatically by Yihui Xie](http://yihui.name/formatr/)

1. А так же божественные комментарии об ошибках


Несколько советов от бати, собственно они применимы ко всей деятельности, и с ними я не раз сталкивался:

* Комментируй код. В комменте пиши "Почему", а не "Что".

* Не пиши в коде строку длиннее чем 80 символов. Тупо неудобно бегать по строке долго глазами. Позаботься о том, кто возможно будет читать твой код.
