--- 
title: "Решение упражнений из книги R Science"
author: "Stas Masuta"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Здесь будут публиковаться решения заданий из книги"
---
--- 
title: "Решение упражнений из книги R Science"
author: "Stas Masuta"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Здесь будут публиковаться решения заданий из книги"
---

---
output: html_document
editor_options:
  chunk_output_type: console
---

# Введение

Это электронная версия решений упражнений, свёрстанная при помощи **bookdown**, который можно установить здесь:

```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

<!--chapter:end:index.Rmd-->


# Предварительный анализ

Placeholder


## Визуализация данных с помощью `ggplot2`
### Введение
### Первые шаги
#### Упражнение 3.2.1 
#### Упражнение 3.2.2 
#### Упражнение 3.2.3 
#### Упражнение 3.2.4 
#### Упражнение 3.2.5 
### Эстетика визуализации
#### Упражнения 3.3.1  
#### Упражнения 3.3.2  
#### Упражнения 3.3.3  
#### Упражнения 3.3.4
#### Упражнения 3.3.5 
#### Упражнения 3.3.6 
### Распространённые ошибки
### Панели
#### Упражнение 3.5.1 
#### Упражнение 3.5.2 
#### Упражнение 3.5.3 
#### Упражнение 3.5.4 
#### Упражнение 3.5.5 
#### Упражнение 3.5.6 
### Геометрические объекты
#### Упражнения 3.6.1 
#### Упражнения 3.6.2 
#### Упражнения 3.6.3 
#### Упражнения 3.6.4 
#### Упражнения 3.6.5 
#### Упражнения 3.6.6 
### Статистические преобразования
#### Упражнения 3.7.1 
#### Упражнения 3.7.2 
#### Упражнения 3.7.3 
#### Упражнения 3.7.4 
#### Упражнения 3.7.5 
### Позиционные настройки
#### Упражнения 3.8.1 
#### Упражнения 3.8.2 
#### Упражнения 3.8.3 
#### Упражнения 3.8.4 
### Системы координат
#### Упражнения 3.9.1 
#### Упражнения 3.9.2 
#### Упражнения 3.9.3 
#### Упражнения 3.9.4 
### Многослойная грамматика графики

<!--chapter:end:1_data_visualisation.Rmd-->



## Рабочий процесс: основы
### Основы написания кода
### Что представляют собой имена
### Вызов функций
#### Упражнение 4.4.1
#### Упражнение 4.4.2
#### Упражнение 4.4.3

<!--chapter:end:2_workflow_basics.Rmd-->



## Преобразование данных с помощью пакета `dplyr`
### Введение
#### Используемые ресурсы
#### Пакет `nycflights13`
#### Основные сведения о пакете `dplyr`
### Фильтрация строк с помощью функции `filter()`
#### Сравнения
#### Логические операторы
#### Отсутствующие значения
#### Упражнение 5.2.4.1 
#### Упражнение 5.2.4.2 
#### Упражнение 5.2.4.3 
#### Упражнение 5.2.4.4 
### Перестановка строк с помощью функции `arange()`
#### Упражнение 5.3.1.1 
#### Упражнение 5.3.1.2
#### Упражнение 5.3.1.3
#### Упражнение 5.3.1.4
### Выбор столбцов с помощью функции `select()`
#### Упражнение 5.4.1.1
#### Упражнение 5.4.1.2
#### Упражнение 5.4.1.3
#### Упражнение 5.4.1.4
### Добавление столбцов с помощью функции `mutate()`
#### Полезные функции создания объектов
#### Упражнение 5.5.2.1
#### Упражнение 5.5.2.2
#### Упражнение 5.5.2.3
#### Упражнение 5.5.2.4
#### Упражнение 5.5.2.5
#### Упражнение 5.5.2.6
### Получение групповых итогов с помощью функции `summarize()`
#### Объединение нескольких операций с помощью канала
#### Отсутствующие значения
#### Счетчики
#### Полезные итоговые функции
#### Группирование по нескольким переменным
#### Разгруппирование
#### Упражнение 5.6.7.1
#### Упражнение 5.6.7.2
#### Упражнение 5.6.7.3
#### Упражнение 5.6.7.4
#### Упражнение 5.6.7.5
#### Упражнение 5.6.7.6
#### Упражнение 5.6.7.7
### Групповое видоизменение (и фильтрация)
#### Упражнение 5.7.1.1
#### Упражнение 5.7.1.2
#### Упражнение 5.7.1.3
#### Упражнение 5.7.1.4
#### Упражнение 5.7.1.5
#### Упражнение 5.7.1.6
#### Упражнение 5.7.1.7

<!--chapter:end:3_data_transformation.Rmd-->



## Организация рабочего процесса: скрипты
### Выполнение кода
### Диагностические средства RStudio
#### Упражнение 6.3.1
#### Упражнение 6.3.2

<!--chapter:end:4_workflow_scripts.Rmd-->


# stocks %>% gather(nazavanie_peremennoy, price, -time)

Placeholder


## Предварительный анализ данных
### Введение
#### Необходимые ресурсы
### Вопросы
### Вариация
#### Визуализация распределений
#### Типичные значения
#### Необычные значения
#### Упражнение 7.3.4.1
#### Упражнение 7.3.4.2
#### Упражнение 7.3.4.3
#### Упражнение 7.3.4.4
### Отсутствующие значения
#### Упражнение 7.3.5.1
#### Упражнение 7.3.5.2
### Ковариация
#### Категориальные и непрерывные переменные
#### Упражнение 7.5.1.1.1
#### Упражнение 7.5.1.1.2
#### Упражнение 7.5.1.1.3
#### Упражнение 7.5.1.1.4
#### Упражнение 7.5.1.1.5
#### Упражнение 7.5.1.1.6
#### Две категориальные переменные
#### Упражнение 7.5.2.1.1
#### Упражнение 7.5.2.1.2
#### Упражнение 7.5.2.1.2
#### Две непрерывные переменные
#### Упражнение 7.5.3.1.1
#### Упражнение 7.5.3.1.2
#### Упражнение 7.5.3.1.3
#### Упражнение 7.5.3.1.4
#### Упражнение 7.5.3.1.5
### Шаблоны поведения переменных и модели
### Вызов функций `ggplot`
### Дополнительная информация

<!--chapter:end:5_exploratory_data_analysis.Rmd-->



## Организация рабочего процесса: проекты
### Что является вашим достоянием
### Где находится ваш анализ
### Пути и каталоги
### Проекты RStudio
### Резюме

<!--chapter:end:6_workflow_projects.Rmd-->


# Подготовка данных

Placeholder


## Создание tibble-фреймов с помощью пакета `tibble`
### Введение
#### Необходимые ресурсы
### Создание tibble-фреймов 
### Сравнение tibble-фреймов с фреймами `data.frame`
#### Вывод на печать
#### Извлечение поднаборов
### Взаимодействие с разработанным ранее кодом
#### Упражнение 10.6.1
#### Упражнение 10.6.2
#### Упражнение 10.6.3
#### Упражнение 10.6.4
#### Упражнение 10.6.5
#### Упражнение 10.6.6

<!--chapter:end:7_tibbles.Rmd-->


# read_delim(file, delim = "|")

Placeholder


## Импорт данных с помощью пакета `reader`
### Введение
#### Необходимые ресурсы
### Приступаем к работе
#### Сравнение с базовыми возможностями R
#### Упражнение 11.2.2.1
#### Упражнение 11.2.2.2
#### Упражнение 11.2.2.3
#### Упражнение 11.2.2.4
#### Упражнение 11.2.2.5
### Синтаксический анализ векторов
#### Парсинг чисел
#### Парсинг строк
#### Факторы
#### Календарные даты, календарные дата и время, время суток
#### Упражнение 11.3.5.1
#### Упражнение 11.3.5.2
#### Упражнение 11.3.5.3
#### Упражнение 11.3.5.4
#### Упражнение 11.3.5.5
#### Упражнение 11.3.5.6
#### Упражнение 11.3.5.7
### Синтаксический анализ файлов
#### Стратегия
#### Проблемы
#### Другие страгтегии 
### Запись в файл
### Другие типы данных

<!--chapter:end:8_data_import.Rmd-->



## Аккуратизация данных с помощью пакета `tidyr`
### Введение
#### Необходимые ресурсы
### Аккуратные данные
#### Упражнения 12.2.1.1
#### Упражнения 12.2.1.2
#### Упражнения 12.2.1.3
### Рассредоточение и сведение столбцов
#### Сведение столбцов (gather)
#### Рассредоточение столбцов (spreading)

<!--chapter:end:9_tidy_data.Rmd-->

